import type { PlayerSheet, StoryState } from '../shared/types.js';
import { GENRES, PLAYER_STAT_MAX, PLAYER_STAT_MIN, PLAYER_STAT_POINTS, RACES } from './config.js';
import { object, text, stringList, clampInt } from './state.js';

export interface CharacterDraftInput { name:string; race:string; genre:string; concept:string; appearance:string; backstory:string; age?:number; gender?:string; bloodline?:string; origin?:string; priorRoleOrTraining?:string; stats?:{PHY:number;MND:number;CHA:number}; desiredAbilities?:string; desiredSpells?:string; inventory?:string; anchors?:string; }
export interface PersonaLike { name?:string; title?:string; description?:string; folder?:string; metadata?:Record<string,unknown>; }

function genrePowerRules(genre:string){
  const g=String(genre||'').trim().toLowerCase();
  if(g==='fantasy'||g==='isekai')return {ability:'Use unmistakably fantasy-native supernatural capability language; avoid scientific/game-system framing.',spell:'Use an unmistakably magical directly activated effect in natural fantasy language.'};
  if(g==='sci-fi')return {ability:'Use a science-fiction-native extraordinary capability grounded in speculative science, augmentation, psionics or setting technology.',spell:'Treat the spell slot as a directly activated science-fiction power/technique, not western fantasy magic unless the concept explicitly mixes them.'};
  if(g==='cyberpunk')return {ability:'Use a cyberpunk-native capability grounded in cyberware, hacking, neural interfaces, drones or plausible setting technology.',spell:'Treat the spell slot as a directly activated extraordinary cybernetic/technical/psionic technique appropriate to the setting; avoid fantasy spell language unless established.'};
  if(g==='wuxia / xianxia')return {ability:'Use a capability native to martial cultivation fiction, with natural technique/cultivation language rather than western spellcraft or game mechanics.',spell:'Use a directly activated mystical cultivation technique native to wuxia/xianxia framing.'};
  if(g==='superhero')return {ability:'Use a concrete directly usable superhero power or extraordinary trained capability consistent with the concept.',spell:'Treat the spell slot as another directly activated superpower/technique rather than assuming literal magic.'};
  if(g==='urban fantasy'||g==='supernatural'||g==='horror')return {ability:'Use a concrete capability native to the established supernatural/occult frame, without inventing powers the concept does not support.',spell:'Use a directly activated occult/supernatural power appropriate to the concept; do not force conventional fantasy spell language.'};
  if(g==='steampunk')return {ability:'Use a steampunk-native extraordinary capability, invention or trained technique consistent with the concept and setting technology.',spell:'Treat the spell slot as a directly activated extraordinary device/technique or magic only when the setting/concept supports it.'};
  return {ability:'Keep the ability native to the selected grounded genre and concept. It may be an exceptional trained technique rather than supernatural. Do not introduce magic, superpowers or impossible technology unless the concept supports them.',spell:'Treat the spell slot as a directly activated exceptional power/technique appropriate to the genre; if the genre is grounded, keep it genre-plausible rather than forcing literal magic.'};
}

export function characterTool(mode:'new'|'convert'='new',stats?:{PHY:number;MND:number;CHA:number}){
  const needsSpell=mode==='new' && Number(stats?.MND||0)>=7;
  return {name:'submit_character_sheet',description:'Submit a grounded Story Engine player sheet using the requested concept and exact stat allocation.',parameters:{type:'object',additionalProperties:false,properties:{name:{type:'string'},race:{type:'string'},genre:{type:'string'},age:{type:'number'},gender:{type:'string'},userNonHuman:{type:'boolean'},bloodline:{type:'string'},origin:{type:'string'},priorRoleOrTraining:{type:'string'},appearance:{type:'string'},stats:{type:'object',additionalProperties:false,properties:{PHY:{type:'integer',minimum:1,maximum:9},MND:{type:'integer',minimum:1,maximum:9},CHA:{type:'integer',minimum:1,maximum:9}},required:['PHY','MND','CHA']},naturalWeapons:{type:'array',items:{type:'string'},maxItems:8},abilities:{type:'array',items:{type:'string'},minItems:mode==='new'?1:0,maxItems:mode==='new'?1:24},spells:{type:'array',items:{type:'string'},minItems:needsSpell?1:0,maxItems:mode==='new'?(needsSpell?1:0):5},inventory:{type:'array',items:{type:'string'}},currency:{type:'array',items:{type:'object',additionalProperties:false,properties:{currency:{type:'string'},amount:{type:'number'}},required:['currency','amount']}},gear:{type:'array',items:{type:'string'}},anchors:{type:'array',items:{type:'string'}},concept:{type:'string'},backstory:{type:'string'}},required:['name','race','genre','appearance','stats','naturalWeapons','abilities','spells','inventory','currency','gear','anchors','concept','backstory']}};
}

export function buildCharacterPrompt(input:CharacterDraftInput){
  const stats=input.stats??{PHY:5,MND:5,CHA:5}; const power=genrePowerRules(input.genre); const explicitAnchors=Boolean(String(input.anchors||'').trim());
  return [
    {role:'system' as const,content:`Create a concise player character sheet for a roleplay simulation. Respect the user's concept; do not add hidden destinies, secret powers, plot armor, unexplained status, or world-breaking advantages. Stats PHY/MND/CHA must each be ${PLAYER_STAT_MIN}-${PLAYER_STAT_MAX} and total exactly ${PLAYER_STAT_POINTS}. The requested allocation is authoritative and must be returned unchanged. Generate exactly ONE deliberately activated, protagonist-grade non-spell ability; format it as Name — concise description. It must grant a concrete useful capability, not a generic skill, passive bonus, numerical modifier, automatic success, or disguised spell. Genre rule for that ability: ${power.ability} Starting spell rule is locked: if MND >= 7 return exactly ONE directly activated offensive or healing genre-appropriate spell/power, formatted as Name — concise description; if MND < 7 return ZERO spells. Genre rule for that spell/power: ${power.spell} Natural weapons are offensive body parts only. Inventory and gear must be plausible for the concept/genre. ${explicitAnchors?'Preserve/refine only the explicitly supplied character anchors; do not add unrelated anchors.':'No character anchors were explicitly supplied, so return an empty anchors array rather than inventing personality/history facts.'} Call submit_character_sheet once.`},
    {role:'user' as const,content:`NAME: ${input.name}\nRACE: ${input.race}\nGENRE: ${input.genre}\nAGE: ${input.age||''}\nGENDER: ${input.gender||''}\nBLOODLINE: ${input.bloodline||''}\nORIGIN: ${input.origin||''}\nPRIOR ROLE / TRAINING: ${input.priorRoleOrTraining||''}\nSTAT ALLOCATION: PHY ${stats.PHY}, MND ${stats.MND}, CHA ${stats.CHA}\nCONCEPT: ${input.concept}\nAPPEARANCE: ${input.appearance}\nBACKSTORY: ${input.backstory}\nDESIRED ABILITIES: ${input.desiredAbilities||''}\nDESIRED SPELLS: ${input.desiredSpells||''}\nINVENTORY IDEAS: ${input.inventory||''}\nANCHORS: ${input.anchors||''}`}
  ];
}

export function buildPersonaConversionPrompt(persona:PersonaLike){
  return [
    {role:'system' as const,content:`Convert the user's CURRENT LUMIVERSE PERSONA into a Story Engine player sheet without changing the original persona. Preserve established identity, appearance, personality, background, possessions, capabilities and genre cues. Do not invent secret powers, plot armor, destiny, wealth or equipment not supported by the persona. Infer a grounded PHY/MND/CHA allocation from the persona: each ${PLAYER_STAT_MIN}-${PLAYER_STAT_MAX}, total exactly ${PLAYER_STAT_POINTS}. A balanced ordinary person should be around 5/5/5; specialize only when the persona clearly supports it. Preserve explicit activated abilities and spells from the persona rather than forcing new-character limits: up to 24 abilities and up to 5 spells. Represent each as Name — concise description when the persona provides enough detail; do not invent missing descriptions. Do not invent missing powers. Preserve explicit gender, age, bloodline, origin, prior role/training and natural weapons when present. Abilities remain descriptive capabilities, never automatic success. Call submit_character_sheet once.`},
    {role:'user' as const,content:`PERSONA NAME: ${persona.name||''}\nTITLE: ${persona.title||''}\nFOLDER: ${persona.folder||''}\nDESCRIPTION:\n${persona.description||''}`}
  ];
}

export function normalizeCharacterSheet(value:unknown,fallback:CharacterDraftInput,mode:'new'|'convert'='new'):PlayerSheet{
  const o=object(value); const st=object(o.stats); let PHY=clampInt(st.PHY,1,9,fallback.stats?.PHY??5),MND=clampInt(st.MND,1,9,fallback.stats?.MND??5),CHA=clampInt(st.CHA,1,9,fallback.stats?.CHA??5);
  if(mode==='new'&&fallback.stats){PHY=fallback.stats.PHY;MND=fallback.stats.MND;CHA=fallback.stats.CHA;}
  else if(PHY+MND+CHA!==PLAYER_STAT_POINTS){ const fixed=normalizeStartingStatBudget({PHY,MND,CHA}); PHY=fixed.PHY;MND=fixed.MND;CHA=fixed.CHA; }
  const abilityLimit=mode==='new'?1:24;const spellLimit=mode==='new'?(MND>=7?1:0):5;
  const abilities=stringList(o.abilities).slice(0,abilityLimit);
  const spells=stringList(o.spells).slice(0,spellLimit);
  const anchors=mode==='new'&&!String(fallback.anchors||'').trim()?[]:stringList(o.anchors).slice(0,12);
  return {name:(mode==='new'?fallback.name:text(o.name))||fallback.name||'Player',race:(mode==='new'?fallback.race:text(o.race))||fallback.race||'Human',genre:(mode==='new'?fallback.genre:text(o.genre))||fallback.genre||'Fantasy',age:Number.isFinite(Number(mode==='new'&&fallback.age!=null?fallback.age:o.age))?Number(mode==='new'&&fallback.age!=null?fallback.age:o.age):(Number.isFinite(Number(fallback.age))?Number(fallback.age):undefined),gender:(mode==='new'&&fallback.gender?fallback.gender:text(o.gender))||fallback.gender||undefined,userNonHuman:typeof o.userNonHuman==='boolean'?o.userNonHuman:undefined,bloodline:(mode==='new'&&fallback.bloodline?fallback.bloodline:text(o.bloodline))||fallback.bloodline||undefined,origin:(mode==='new'&&fallback.origin?fallback.origin:text(o.origin))||fallback.origin||undefined,priorRoleOrTraining:(mode==='new'&&fallback.priorRoleOrTraining?fallback.priorRoleOrTraining:text(o.priorRoleOrTraining))||fallback.priorRoleOrTraining||undefined,appearance:text(o.appearance)||fallback.appearance||'',stats:{PHY,MND,CHA},naturalWeapons:stringList(o.naturalWeapons).slice(0,8),abilities,spells,inventory:stringList(o.inventory).slice(0,40),currency:Array.isArray(o.currency)?o.currency.slice(0,12) as any:[],gear:stringList(o.gear).slice(0,20),anchors,concept:text(o.concept)||fallback.concept,backstory:text(o.backstory)||fallback.backstory,wounds:[],conditions:[],tasks:[],commitments:[]};
}

export function normalizeConvertedPersonaSheet(value:unknown,persona:PersonaLike):PlayerSheet{
  const fallback:CharacterDraftInput={name:text(persona.name)||'Player',race:'Human',genre:'Fantasy',concept:text(persona.title),appearance:'',backstory:text(persona.description),stats:{PHY:5,MND:5,CHA:5}};
  return normalizeCharacterSheet(value,fallback,'convert');
}

export function validateCharacterInput(input:CharacterDraftInput):string[]{ const errors:string[]=[]; if(!input.name.trim())errors.push('Name is required.'); if(!RACES.includes(input.race as any))errors.push('Choose a supported race.'); if(!GENRES.includes(input.genre as any))errors.push('Choose a supported genre.'); if(input.stats){const vals=[input.stats.PHY,input.stats.MND,input.stats.CHA]; if(vals.some(v=>v<PLAYER_STAT_MIN||v>PLAYER_STAT_MAX))errors.push(`Each stat must be ${PLAYER_STAT_MIN}-${PLAYER_STAT_MAX}.`); if(vals.reduce((a,b)=>a+b,0)!==PLAYER_STAT_POINTS)errors.push(`PHY + MND + CHA must equal ${PLAYER_STAT_POINTS}.`);} return errors; }
export function renderPersonaDescription(sheet:PlayerSheet):string { return `BASIC INFO\nName: ${sheet.name}\nRace: ${sheet.race}${sheet.gender?`\nGender: ${sheet.gender}`:''}${sheet.age?`\nAge: ${sheet.age}`:''}${sheet.bloodline?`\nBloodline: ${sheet.bloodline}`:''}${sheet.origin?`\nOrigin: ${sheet.origin}`:''}${sheet.priorRoleOrTraining?`\nPrior role / training: ${sheet.priorRoleOrTraining}`:''}\nGenre: ${sheet.genre}\n\nAPPEARANCE\n${sheet.appearance}\n\nSTATS\nPHY: ${sheet.stats.PHY}\nMND: ${sheet.stats.MND}\nCHA: ${sheet.stats.CHA}\n\nNATURAL WEAPONS\n${bullets(sheet.naturalWeapons)}\n\nABILITIES\n${bullets(sheet.abilities)}\n\nSPELLS\n${bullets(sheet.spells)}\n\nINVENTORY\n${bullets(sheet.inventory)}\n\nCURRENCY\n${sheet.currency.length?sheet.currency.map(c=>`- ${c.amount} ${c.currency}`).join('\n'):'- None'}\n\nGEAR\n${bullets(sheet.gear)}\n\nCHARACTER ANCHORS\n${bullets(sheet.anchors)}${sheet.backstory?`\n\nBACKSTORY\n${sheet.backstory}`:''}`; }
export function applyPlayerToState(state:StoryState,sheet:PlayerSheet){state.player=sheet; state.health.user.maxHp=Math.max(10,state.health.user.maxHp); state.health.user.currentHp=Math.min(state.health.user.maxHp,Math.max(1,state.health.user.currentHp)); state.names.style=state.names.style||'Balanced Fantasy';}
function bullets(v:string[]){return v.length?v.map(x=>`- ${x}`).join('\n'):'- None';}
export function normalizeStartingStatBudget(s:{PHY:number;MND:number;CHA:number}){const out={...s}; let total=out.PHY+out.MND+out.CHA; const keys=['PHY','MND','CHA'] as const; while(total<PLAYER_STAT_POINTS){const k=[...keys].sort((a,b)=>out[a]-out[b])[0]!;if(out[k]>=PLAYER_STAT_MAX)break;out[k]++;total++;} while(total>PLAYER_STAT_POINTS){const k=[...keys].sort((a,b)=>out[b]-out[a])[0]!;if(out[k]<=PLAYER_STAT_MIN)break;out[k]--;total--;}return out;}
